server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      #集群用这个
      #      connect-string: 192.168.1.104:2181,192.168.1.105:2181,192.168.1.106:2181
      #单机用这个
      connect-string: 192.168.1.102:2181