server:
  port: 8001

spring:
  application:
    name: cloud-payment-service #名称很重要，不能随意更改，因为这个服务名称会注册进Eureka中

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #数据源
    driver-class-name: org.gjt.mm.mysql.Driver     #驱动
    url: jdbc:mysql://192.168.1.103:3306/db2019?useUnicode=true&characterEncoding=utf-8&userSSL=false&verifyServerCertificate=false&serverTimezone=UTC
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka/  #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dengooo.springcloud.entities   #entity

