server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #数据源
    driver-class-name: org.gjt.mm.mysql.Driver     #驱动
    url: jdbc:mysql://192.168.1.103:3306/db2019?useUnicode=true&characterEncoding=utf-8&userSSL=false&verifyServerCertificate=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dengooo.springcloud.entities   #entity