server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进eureka的微服务名称

  cloud:
    config:
      server:
        git:
          uri: https://github.com/denghang96/springcloud-config.git #GitHub上的git仓库名字
          search-paths: #搜索目录
            - springcloud-config
      label: master #master分支
  rabbitmq:
    host: 192.168.1.107
    port: 5672
    username: root
    password: 123456
    virtual-host: dengooo
#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/