server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #  defaultZone: http://localhost:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/  #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
  server:
    # 关闭自我保护机制，保证不可用服务被及时踢除 .默认是开启的，自我保护机制的解释就是，当一段时间内有一部分服务跟Server停止了心跳，则本来应该将改服务从Eureka中移除掉了
    # 但是如果这个时间段内Client的心跳丢失的过多，Eureka就担心是网络故障引起的，而本身Cilent微服务是正常的，只需要等网络恢复，Client微服务就继续可以接着用
    # 关闭掉的意思就是，只要心跳没了，超过了一定时间就移除掉，默认是9000毫秒，这里改成2000毫秒
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000