server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: 192.168.1.102
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://${spring.cloud.consul.host}:8500
