server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      #集群用这个
      #      connect-string: 192.168.1.104:2181,192.168.1.105:2181,192.168.1.106:2181
      #单机用这个
      connect-string: 192.168.1.102:2181
#Feign的超时控制
ribbon:
  ReadTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnetTimeout: 5000 #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间.

feign:
  hystrix:
    enabled: true #客户端的服务降级，我们是用feign调用的，所以打开hystrix